name: Generate glossary

on:
  schedule:
    - cron: '0 5 * * * '
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      GS_CLIENT_EMAIL: ${{ secrets.GS_CLIENT_EMAIL }}
      GS_PRIVATE_KEY: ${{ secrets.GS_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
          cache: npm
      - run: npm install google-spreadsheet
      - run: node scripts/glossary.js
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "<>"
          git add terms.tbx
          git commit -m "Glossary file update" || echo "Nothing to commit"
          git push
