name: Validate translation

on:
  push:
    branches:
    - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      GS_CLIENT_EMAIL: ${{ secrets.GS_CLIENT_EMAIL }}
      GS_PRIVATE_KEY: ${{ secrets.GS_PRIVATE_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm install
    - run: node scripts/l10n.js stats -sfp source/l10n/cs/
    - run: node scripts/l10n.js validate source/l10n/cs/
    - run: ./build.sh
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: generated
        path: target/text
