name: Validate translation

on:
  push:
    branches:
    - main

jobs:
  validate:
    runs-on: ubuntu-latest
    env: 
      GGCLIENT_EMAIL: ${{ secrets.GGCLIENT_EMAIL }}
      GGPRIVATE_KEY: ${{ secrets.GGPRIVATE_KEY }}   
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm install
    - run: node scripts/l10n.js stats -sf source/l10n/cs/
    - run: node scripts/l10n.js statspush -p
    - run: node scripts/l10n.js validate source/l10n/cs/
    - run: ./build.sh
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: generated
        path: target/text
